######TEST
######TEST
######TEST
######TEST
######TEST
######TEST
name: 'test github action'
on:
  push:
    branches:
      - main #set test branch

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: getSlackID
        id: firstStepId
        uses: KanghyunJeon/github-slack-id-mapper-action@v0.0.3
        with:
          github-developer-id-mapping: "KanghyunJeon:UUABCDEFG,member:UuHIJKLMN" # Required, need to set github repository vaiables ex) KanghyunJeon:UUABCDEFG,member:UuHIJKLMN'
          github-user-id: ${{ github.event.pusher.name }} # Required   ex) KanghyunJeon

      - name: doOtherJobs
        run: echo "SlackID = ${{ steps.firstStepId.outputs.slack-user-id }}"